name: Deploy to Google Cloud Functions
on:
  push:
    branches:
      - main

jobs:
  get-secrets:
    runs-on: ubuntu-latest  

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token-format: 'access-token'
        workload_identity_provider: 'projects/222808868980/locations/global/workloadIdentityPools/github-actions-cloud-run/providers/github'
        service_account: 'github-actions-cloud-run@fenixwork-projects.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - id: 'gcloud'
      name: 'gcloud'
      run: |-
          gcloud secrets versions access "latest" --secret "my-secret"